### ISSUE TITLE
Threshold Value 

### ISSUE THREAD

**Issue by collinr2** [yanwu20/ASPIRER#2]
I managed to get the test code to work. But I am now creating a prediction for my own dataset. However I am confused by the threshold. Am I supposed to create my own threshold for each dataset or is there a numeric value which I can assign to the threshold? 

Thanks for your help!

**Comment by yanwu20** [comment]
The default threshold is 0.5. The threshold sets the minimum probability needed for a positive prediction. It is a trade-off between precision and recall. Increasing the threshold tends to decrease the number of false positive samples, but it may also increase the number of false negatives.

**Comment by collinr2** [comment]
Hi,

Thank you for your help! So just checking: 

python ASPIRER.py --type predict --Fasta_file /scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/dataset/example.fasta --PSSM_file /scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/features/example_pse_pssm.csv --output_name /scale_wlg_persistent/filesets/project/vuw03925/software/ASPIRER/ASPIRER/output/example_result.csv --threshold 0.5

would be correct? 

Thanks again!

**Comment by yanwu20** [comment]
Yeah, it is correct.

**Comment by collinr2** [comment]
Thank you!
